services:
  bank-discovery-service:
    build: ./discovery-service
    container_name: bank-discovery-service
    ports:
      - '8761:8761'
    expose:
      - '8761'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
    networks:
      - e-bank-network

  bank-config-service:
    build: ./config-service
    container_name: bank-config-service
    ports:
      - '9999:9999'
    expose:
      - '9999'
    environment:
      - DISCOVERY_SERVICE_URL=http://bank-discovery-service:8761/eureka
    depends_on:
      bank-discovery-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9999/actuator/health"]
      interval: 10s
    networks:
      - e-bank-network

  bank-customer-service:
    build: ./customer-service
    container_name: bank-customer-service
    ports:
      - '8081:8081'
    expose:
      - '8081'
    environment:
      - DISCOVERY_SERVICE_URL=http://bank-discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://bank-config-service:9999
    depends_on:
      bank-config-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 10s
    networks:
      - e-bank-network

  bank-account-service:
    build: ./account-service
    container_name: bank-account-service
    ports:
      - '8082:8082'
    expose:
      - '8082'
    environment:
      - DISCOVERY_SERVICE_URL=http://bank-discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://bank-config-service:9999
    depends_on:
      bank-customer-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/actuator/health"]
      interval: 10s
    networks:
      - e-bank-network

  bank-gateway-service:
    build: ./gateway-service
    container_name: bank-gateway-service
    ports:
      - '8888:8888'
    expose:
      - '8888'
    environment:
      - DISCOVERY_SERVICE_URL=http://bank-discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://bank-config-service:9999
    depends_on:
      bank-config-service:
        condition: service_healthy
    networks:
      - e-bank-network

  front-end:
    build: ./front-end
    container_name: bank-front-end
    ports:
      - '80:80'
    expose:
      - '80'
    networks:
      - e-bank-network

  mysql-container:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: b@b@prince
    networks:
      - e-bank-network
    ports:
      - '3309:3306'

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    networks:
      - e-bank-network
    ports:
      - '82:80'
    depends_on:
      - mysql-container
    environment:
      PMA_HOST: mysql-container
      PMA_PORT: 3306
    restart: always

networks:
  e-bank-network:
    driver: bridge